[package]
name = "myService"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "myService"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.6.15"
lazy_static = "1.4.0"
async-std = "1.10"  # Use async-std for async tasks if appropriate
tokio = "1.38.0"
surrealdb = "1.5.1"
serde = "1.0.203"
ring = "0.17.8"
# surrealdb = "1.5.1" # Ensure `surrealdb` is WASM-compatible or replaced


[dev-dependencies]
marine-rs-sdk-test = "0.16.1"
